sudo: false
language: node_js
node_js:
- 5.4.1
before_script:
- npm i
script:
- npm test
- npm run build
cache:
  bundler: true
  directories:
  - node_modules
before_deploy:
  - pip install --user awscli
  - ~/.local/bin/aws configure set preview.cloudfront true
deploy:
  provider: script
  script: ~/.local/bin/aws s3 sync dist $BUCKET $REGION --delete
  skip_cleanup: true
  on:
    branch: master
after_deploy: ~/.local/bin/aws cloudfront create-invalidation --distribution-id $DIST_ID --paths '/*'
notifications:
